app:
  datasource:
    jdbcUrl: jdbc:h2:./build/db/wpbooker
    driverClass: org.h2.Driver
    user: wpbooker
    password: wpbooker
    checkoutTimeout: 500

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    rest:
      default-media-type: application/json
